### ISSUE TITLE
Error: `undefined method `[]' for #<Set: {#<MIME::Type: application/json>}>`

### ISSUE THREAD

**Issue by urfolomeus** [mailjet/mailjet-gem#68]
I'm seeing the above error whenever I try to call any Mailjet methods from a Rails app. I can make any of the calls fine via curl or even via a plain Ruby app, but no calls at all from Rails. I'm probably doing something stupid but I can't figure it out.

Running this in curl works fine (where `<api_key>` and `<secret_key>` are the provided keys):

```shell
curl -s \
    -X POST \
    --user "<api_key>:<secret_key>" \
    https://api.mailjet.com/v3/send \
    -H "Content-Type: application/json" \
    -d '{
        "FromEmail":"alan@example.com",
        "FromName":"Me",
        "Recipients": [ 
            {
            "Email":"bobby@example.com"
            }
        ],
        "Subject":"My first Mailjet Email!",
        "Text-part":"Greetings from Mailjet."
    }'
```

Running this ruby script also works fine:

```ruby
require 'rubygems'
require 'mailjet'

Mailjet.configure do |config|
  config.api_key      = <api_key>
  config.secret_key   = <secret_key>
  config.default_from = 'alan@example.com'
end

p recipients: Mailjet::Listrecipient.all
```

However this, in a brand new Rails app (4.2.6) gives the error we mentioned:

```ruby
# config/initializers/mailjet.rb
Mailjet.configure do |config|
  config.api_key      = <api_key>
  config.secret_key   = <secret_key>
  config.default_from = 'alan@example.com'
end

# in `rails console`
p recipients: Mailjet::Listrecipient.all
```

Full error text:

```ruby
NoMethodError: undefined method `[]' for #<Set: {#<MIME::Type: application/json>}>
	from /Users/alan/.rvm/gems/ruby-2.3.0@mail_spike/gems/rest-client-1.6.7/lib/restclient/request.rb:307:in `type_for_extension'
	from /Users/alan/.rvm/gems/ruby-2.3.0@mail_spike/gems/rest-client-1.6.7/lib/restclient/request.rb:312:in `type_for_extension'
	from /Users/alan/.rvm/gems/ruby-2.3.0@mail_spike/gems/rest-client-1.6.7/lib/restclient/request.rb:286:in `block (2 levels) in stringify_headers'
	from /Users/alan/.rvm/gems/ruby-2.3.0@mail_spike/gems/rest-client-1.6.7/lib/restclient/request.rb:286:in `map'
	from /Users/alan/.rvm/gems/ruby-2.3.0@mail_spike/gems/rest-client-1.6.7/lib/restclient/request.rb:286:in `block in stringify_headers'
	from /Users/alan/.rvm/gems/ruby-2.3.0@mail_spike/gems/rest-client-1.6.7/lib/restclient/request.rb:272:in `each'
	from /Users/alan/.rvm/gems/ruby-2.3.0@mail_spike/gems/rest-client-1.6.7/lib/restclient/request.rb:272:in `inject'
	from /Users/alan/.rvm/gems/ruby-2.3.0@mail_spike/gems/rest-client-1.6.7/lib/restclient/request.rb:272:in `stringify_headers'
	from /Users/alan/.rvm/gems/ruby-2.3.0@mail_spike/gems/rest-client-1.6.7/lib/restclient/request.rb:92:in `make_headers'
	from /Users/alan/.rvm/gems/ruby-2.3.0@mail_spike/gems/rest-client-1.6.7/lib/restclient/request.rb:58:in `initialize'
	from /Users/alan/.rvm/gems/ruby-2.3.0@mail_spike/gems/rest-client-1.6.7/lib/restclient/request.rb:33:in `new'
	from /Users/alan/.rvm/gems/ruby-2.3.0@mail_spike/gems/rest-client-1.6.7/lib/restclient/request.rb:33:in `execute'
	from /Users/alan/.rvm/gems/ruby-2.3.0@mail_spike/gems/rest-client-1.6.7/lib/restclient/resource.rb:51:in `get'
	from /Users/alan/.rvm/gems/ruby-2.3.0@mail_spike/gems/mailjet-1.3.8/lib/mailjet/connection.rb:65:in `handle_api_call'
	from /Users/alan/.rvm/gems/ruby-2.3.0@mail_spike/gems/mailjet-1.3.8/lib/mailjet/connection.rb:43:in `get'
	from /Users/alan/.rvm/gems/ruby-2.3.0@mail_spike/gems/mailjet-1.3.8/lib/mailjet/resource.rb:58:in `all'
... 11 levels...
	from /Users/alan/.rvm/gems/ruby-2.3.0@mail_spike/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
	from /Users/alan/.rvm/gems/ruby-2.3.0@mail_spike/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `block in load'
	from /Users/alan/.rvm/gems/ruby-2.3.0@mail_spike/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/alan/.rvm/gems/ruby-2.3.0@mail_spike/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
	from /Users/alan/.rvm/gems/ruby-2.3.0@mail_spike/gems/spring-1.6.4/lib/spring/commands/rails.rb:6:in `call'
	from /Users/alan/.rvm/gems/ruby-2.3.0@mail_spike/gems/spring-1.6.4/lib/spring/command_wrapper.rb:38:in `call'
	from /Users/alan/.rvm/gems/ruby-2.3.0@mail_spike/gems/spring-1.6.4/lib/spring/application.rb:185:in `block in serve'
	from /Users/alan/.rvm/gems/ruby-2.3.0@mail_spike/gems/spring-1.6.4/lib/spring/application.rb:156:in `fork'
	from /Users/alan/.rvm/gems/ruby-2.3.0@mail_spike/gems/spring-1.6.4/lib/spring/application.rb:156:in `serve'
	from /Users/alan/.rvm/gems/ruby-2.3.0@mail_spike/gems/spring-1.6.4/lib/spring/application.rb:131:in `block in run'
	from /Users/alan/.rvm/gems/ruby-2.3.0@mail_spike/gems/spring-1.6.4/lib/spring/application.rb:125:in `loop'
	from /Users/alan/.rvm/gems/ruby-2.3.0@mail_spike/gems/spring-1.6.4/lib/spring/application.rb:125:in `run'
	from /Users/alan/.rvm/gems/ruby-2.3.0@mail_spike/gems/spring-1.6.4/lib/spring/application/boot.rb:18:in `<top (required)>'
	from /Users/alan/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/alan/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
```

Is there something that we're missing? You can view the sample Rails app at <https://github.com/urfolomeus/mail_spike>

**Comment by GuillaumeBadi** [comment]
Hey @urfolomeus !

Where do you `require 'mailjet'`? (maybe a stupid question, I am not a Rails expert)

**Comment by urfolomeus** [comment]
Hi @GuillaumeBadi. Thanks for the quick reply!

Gems are required automatically via Bundler if they are in your Gemfile.

**Comment by urfolomeus** [comment]
You can see this if you launch the Rails console and then try to require 'mailjet'. The console responds with `false` because the gem is already required.

```ruby
» rails c
Running via Spring preloader in process 8988
Loading development environment (Rails 4.2.6)
2.3.0 :001 > require 'mailjet'
 => false
```

**Comment by GuillaumeBadi** [comment]
I wonder if it is not related to this : https://github.com/urfolomeus/mail_spike/blob/632aaaa730ad532f81422751f5b4185fe3e6f6d3/config/initializers/mime_types.rb

Might be something to do here, I am trying to make it work on my side too

**Comment by urfolomeus** [comment]
@GuillaumeBadi `application/json` should be included out of the box, but there could be something around that.

I cracked open the gem using `bundle open` and set a bunch of puts debugs around the `Mailjet::Resource.all` method to see where it was going wrong, but it's not even getting as far as that method.

**Comment by GuillaumeBadi** [comment]
It's really strange that it works outside rails

**Comment by urfolomeus** [comment]
Yeah, that's what has me baffled :grin:

**Comment by GuillaumeBadi** [comment]
This guy made it work : https://github.com/elyrly/datahackathon, but I can't spot the differences, even if you change the wrapper version to the last one (1.3.8)

**Comment by urfolomeus** [comment]
He's using an older version of Rails (4.1.1) which might have something to do with it. I'm just heading home now but will check it out later. Thanks.

**Comment by urfolomeus** [comment]
@GuillaumeBadi found it! The issue actually lies in RestClient (as I would have realised sooner had I _actually_ read the stack trace properly 😉). Essentially RestClient is expecting an array at one point but gets a Set instead. I'll raise this issue with them and see if I can get my fix merged.

Thanks.

**Comment by urfolomeus** [comment]
Actually it looks like we were on an old version of the rest-client gem (1.6.7). We added `gem rest-client '~>1.6.9'` to our Gemfile, then ran `bundle update` to resolve dependency clashes, and that got rid of the issue.

I'm not sure if it's worth you locking rest-client similarly in mailjet-gem or whether a note in the README might suffice?

**Comment by GuillaumeBadi** [comment]
Updating the rest-client dependency looks to be working. I am going to test it a little deeper and probably merge it. Thanks for your help!

**Comment by urfolomeus** [comment]
No problem. Thanks for yours 🙂

**Comment by jjb** [comment]
@GuillaumeBadi just FYI this helped me solve the same problem in a completely unrelated project :-D. thanks! 🙏

**Comment by GuillaumeBadi** [comment]
Glad it helped!

**Comment by jagadeeswar577** [comment]
Updating the rest-clien worked, thank you :)
